language: generic 
sudo: required 
services:
  - docker 

before_install:
  - docker build -t jblackwell/react-test -f ./client/Dockerfile.dev ./client 

script: 
  - docker run -e CI=true jblackwell/react-test npm test 

after_success: 
  - docker build -t jblackwell1/multi-client ./client
  - docker build -t jblackwell1/multi-nginx  ./nginx 
  - docker build -t jblackwell1/multi-server ./server 
  - docker build -t jblackwell1/multi-worker ./worker 
# log into  docker cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
# take those images and push to docker hub
  - docker push jblackwell1/multi-client 
  - docker push jblackwell1/multi-nginx 
  - docker push jblackwell1/multi-server 
  - docker push jblackwell1/multi-worker 

deploy: 
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env 
  bucket_name: elasticbeanstalk-us-east-1-706248667117
  bucket_path: docker-multi 
  on: 
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY 